# -*- coding: utf-8 -*-
"""Build Search Index.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kJmkf7TulplvWn9CcebG_oNIaWx1e7Gs
"""

!nvidia-smi

# ============================================================
# PhysicsHub — build_search_index.py
# Google Colab READY (GPU ENABLED)
# ============================================================

import sys
import subprocess

subprocess.check_call([
    sys.executable, "-m", "pip", "install", "-q",
    "sentence-transformers>=3.0,<6",
    "numpy>=1.26,<3"
])

import hashlib
import json
import math
import re
import struct
import zipfile
from collections import Counter, defaultdict
from pathlib import Path
from google.colab import files

MODEL_NAME = "sentence-transformers/all-MiniLM-L6-v2"
VECTOR_DIMENSIONS = 384
VECTOR_MAGIC = 0x50585631  # ASCII "PXV1"
VECTOR_VERSION = 1

STOPWORDS = set("""
a an and are as at be been being by can could did do does for from had has have
how i if in into is it its may more most of on or our should than that the their
them then there these they this to under was we were what when where which who why
will with would you your
""".split())

def get_text(question):
    """Safely extract text favoring question_markdown, falling back to Question_metadata."""
    return str(question.get("question_markdown") or question.get("Question_metadata") or "").strip()

def normalize_text(value):
    import unicodedata
    text = unicodedata.normalize("NFKC", str(value or ""))
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"!\[[^\]]*\]\([^)]*\)", " ", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)
    text = text.lower()
    text = re.sub(r"\\(?:left|right|rm|mathbf|mathrm|text|vec|hat|bar|cdot|times|frac|dfrac|sqrt|operatorname)\b", " ", text)
    text = re.sub(r"\\[a-z]+", " ", text)
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()

def tokenize(value):
    return [token for token in normalize_text(value).split() if len(token) > 1 and token not in STOPWORDS]

def canonical_text(value):
    text = str(value or "")
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"!\[[^\]]*\]\([^)]*\)", " ", text)
    text = re.sub(r"\[([^\]]+)\]\([^)]*\)", r"\1", text)
    text = re.sub(r"[*_~`]", "", text)
    text = re.sub(r"\\[,;!: ]", "", text)
    text = re.sub(r"\$\$|\$|\\\(|\\\)|\\\[|\\\]", " ", text)
    text = re.sub(r"(^|\n)\s*(?:[-*•]\s*)?\((?:i{1,3}|iv|v|vi{0,3})\)\s*", r"\1", text, flags=re.I)
    text = re.sub(r"(^|\n)\s*(?:[-*•]\s*)?\d+\s*[\.\):\-]\s*", r"\1", text)
    text = re.sub(r"\b(?:cse|ifos)\b", " ", text, flags=re.I)
    text = re.sub(r"\b(?:19|20)\d{2}\b", " ", text)
    text = re.sub(r"\b\d+\s*m(?:arks?)?\b", " ", text, flags=re.I)
    return normalize_text(text)

def formula_normalize(value):
    return str(value or "").lower().replace("−", "-").replace("·", "*").replace("×", "*")

def extract_formulas(value):
    formulas = []
    pattern = r"(\$\$[\s\S]*?\$\$|\$[^$\n]+\$|\\\(.*?\\\)|\\\[.*?\\\])"
    for match in re.findall(pattern, str(value or "")):
        formula = formula_normalize(match)
        formula = re.sub(r"\\(?:left|right|rm|mathrm|mathbf|vec|hat|bar|cdot|times|frac|dfrac|sqrt|text)\b", "", formula)
        formula = re.sub(r"[\s{}$()[\]]+", "", formula)
        formula = re.sub(r"[^a-z0-9=+\-*/^.,_:<>]", "", formula)
        if len(formula) >= 3:
            formulas.append(formula)
    return sorted(set(formulas))

def corpus_text(question):
    topics = question.get("syllabus_topic") or []
    if not isinstance(topics, list):
        topics = [topics]
    return " ".join([
        get_text(question),
        str(question.get("unit", "")),
        str(question.get("section", "")),
        *[str(topic) for topic in topics]
    ])

def repository_fingerprint(questions):
    payload = [(
        q.get("id"), get_text(q), q.get("exam"), q.get("year"),
        q.get("marks"), q.get("unit"), q.get("section"), q.get("syllabus_topic", [])
    ) for q in questions]
    raw = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return hashlib.sha256(raw.encode("utf-8")).hexdigest()

def build_index(questions):
    documents = []
    exact_groups = defaultdict(list)
    formula_list = []

    for index, question in enumerate(questions):
        text = get_text(question)
        if not text:
            raise ValueError(f"Question {index} (ID: {question.get('id')}) has empty text.")

        corpus = corpus_text(question)
        documents.append(tokenize(corpus))

        key = canonical_text(text)
        if len(key) >= 18:
            exact_groups[key].append(index)

        formula_list.append(extract_formulas(text))

    # TF-IDF
    document_frequency = Counter()
    for tokens in documents:
        document_frequency.update(set(tokens))

    count = len(documents)
    idf = {token: math.log((count + 1) / (frequency + 1)) + 1 for token, frequency in document_frequency.items()}

    postings = defaultdict(list)
    document_norms = [0.0] * count

    for doc_index, tokens in enumerate(documents):
        frequencies = Counter(tokens)
        squared_sum = 0.0
        for token, frequency in frequencies.items():
            weight = ((1 + math.log(frequency)) * idf[token])
            squared_sum += weight * weight
            postings[token].append([doc_index, round(weight, 6)])
        document_norms[doc_index] = round(math.sqrt(squared_sum) or 1.0, 6)

    exact_groups_list = [indices for indices in exact_groups.values() if len(indices) > 1]

    return {
        "version": 4,
        "count": count,
        "questionFingerprint": repository_fingerprint(questions),
        "embeddingModel": MODEL_NAME,
        "embeddingDimensions": VECTOR_DIMENSIONS,
        "documents": [
            {
                "id": str(q.get("id", "")),
                "question": get_text(q),
                "exam": q.get("exam", ""),
                "year": q.get("year", 0),
                "marks": q.get("marks", ""),
                "unit": q.get("unit", ""),
                "section": q.get("section", ""),
                "syllabus_topic": q.get("syllabus_topic", []),
                "exact_key": canonical_text(get_text(q)),
                "formulas": formulas
            }
            for q, formulas in zip(questions, formula_list)
        ],
        "exactGroups": exact_groups_list,
        "tfidf": {
            "idf": idf,
            "postings": dict(postings),
            "docNorms": document_norms
        }
    }

def build_vectors(questions, output_path):
    from sentence_transformers import SentenceTransformer
    import numpy as np

    print("\n" + "=" * 72)
    print("Loading:", MODEL_NAME)
    print("=" * 72 + "\n")

    # GPU implicitly used if available (no device="cpu" bottleneck)
    model = SentenceTransformer(MODEL_NAME)

    texts = [corpus_text(question) for question in questions]
    print(f"Generating vectors for {len(texts):,} PYQs...\n")

    embeddings = model.encode(
        texts,
        batch_size=64,
        show_progress_bar=True,
        normalize_embeddings=True,
        convert_to_numpy=True
    )

    embeddings = np.asarray(embeddings, dtype=np.float32, order="C")

    if embeddings.ndim != 2:
        raise RuntimeError(f"Unexpected embedding shape: {embeddings.shape}")
    if embeddings.shape[0] != len(questions):
        raise RuntimeError("Vector count does not match question count.")
    if embeddings.shape[1] != VECTOR_DIMENSIONS:
        raise RuntimeError(f"Expected {VECTOR_DIMENSIONS} dimensions, got {embeddings.shape[1]}.")

    with open(output_path, "wb") as file:
        file.write(struct.pack("<IIII", VECTOR_MAGIC, VECTOR_VERSION, embeddings.shape[0], embeddings.shape[1]))
        file.write(embeddings.tobytes(order="C"))

    print(f"\nVector file: {output_path}")
    print(f"Size: {output_path.stat().st_size / 1024 / 1024:.2f} MiB")

def main():
    print("=" * 72)
    print("PhysicsHub — Analysis Index Builder")
    print("Google Colab (GPU Accelerated)")
    print("No WebLLM • No API • Client-side runtime")
    print("=" * 72 + "\n")

    print("Please upload your current questions.json file.\n")
    uploaded = files.upload()

    if not uploaded:
        raise RuntimeError("No file was uploaded.")

    filename = "questions.json" if "questions.json" in uploaded else [name for name in uploaded if name.lower().endswith(".json")][0]
    questions_path = Path("questions.json")
    questions_path.write_bytes(uploaded[filename])

    with open(questions_path, "r", encoding="utf-8") as file:
        questions = json.load(file)

    if not isinstance(questions, list) or not questions:
        raise RuntimeError("questions.json must contain a non-empty top-level array.")

    required = ["id", "exam", "year", "unit", "section", "syllabus_topic"]

    for i, question in enumerate(questions):
        if not isinstance(question, dict):
            raise RuntimeError(f"Question {i} is not a JSON object.")
        missing = [field for field in required if field not in question]
        if missing:
            raise RuntimeError(f"Question {i} ({question.get('id', 'NO-ID')}) is missing: {missing}")
        if not get_text(question):
            raise RuntimeError(f"Question {i} ({question.get('id', 'NO-ID')}) is missing valid markdown/metadata text.")

    print(f"\nLoaded {len(questions):,} PYQs.")
    print("Repository fingerprint:", repository_fingerprint(questions))
    print("\nBuilding exact + TF-IDF + formula index...")

    index = build_index(questions)

    output_dir = Path("physics_hub_analysis_index")
    if output_dir.exists():
        import shutil
        shutil.rmtree(output_dir)

    data_dir = output_dir / "data"
    data_dir.mkdir(parents=True, exist_ok=True)

    index_path = data_dir / "analysis-index.json"
    vector_path = data_dir / "analysis-vectors.bin"

    index_path.write_text(json.dumps(index, ensure_ascii=False, separators=(",", ":")), encoding="utf-8")
    build_vectors(questions, vector_path)

    zip_path = Path("physics_hub_analysis_index.zip")
    if zip_path.exists():
        zip_path.unlink()

    with zipfile.ZipFile(zip_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in data_dir.iterdir():
            archive.write(path, arcname=f"data/{path.name}")

    print("\n" + "=" * 72)
    print("BUILD COMPLETE")
    print("=" * 72 + "\n")
    print(f"PYQs:             {len(questions):,}")
    print(f"Exact groups:     {len(index['exactGroups']):,}")
    print(f"TF-IDF terms:     {len(index['tfidf']['idf']):,}")
    print(f"Vector dimensions:{VECTOR_DIMENSIONS}")
    print(f"Vector file:      {vector_path.stat().st_size / 1024 / 1024:.2f} MiB")
    print(f"ZIP:              {zip_path.stat().st_size / 1024 / 1024:.2f} MiB\n")
    print("Downloading deployment bundle...")

    files.download(str(zip_path))

if __name__ == "__main__":
    main()