# -*- coding: utf-8 -*-
"""PYQ Topic Tagger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mziH47OWDft0pcJo_sL-qHgoz8BpKr7o
"""

import json
import time
import getpass
import sys
from pydantic import BaseModel, Field
from typing import List
from google.colab import files
from google import genai
from google.genai import types

# ==========================================
# 1. Initialization and File Uploads
# ==========================================
print("🔑 Securely initialize the Gemini client")
api_key = getpass.getpass("Enter your Gemini API Key: ")
client = genai.Client(api_key=api_key)

GEMINI_MODEL = "gemini-3.5-flash-lite"  # Use stable production model name
BATCH_SIZE = 40

print("\n📂 Please upload 'questions.json' and 'syllabus.json'")
uploaded = files.upload()

INPUT_JSON = "questions.json"
SYLLABUS_JSON = "syllabus.json"
OUTPUT_JSON = "topic_tagged_questions.json"
FAILED_QUESTIONS_JSON = "failed_questions.json"

if INPUT_JSON not in uploaded or SYLLABUS_JSON not in uploaded:
    raise FileNotFoundError("Please ensure both 'questions.json' and 'syllabus.json' are uploaded.")

with open(INPUT_JSON, "r", encoding="utf-8") as f:
    questions = json.load(f)

with open(SYLLABUS_JSON, "r", encoding="utf-8") as f:
    syllabus_data = json.load(f)

# ==========================================
# 2. Strict Pre-Check Validation
# ==========================================
print("\n🔍 Running strict pre-check for unique IDs and valid question_markdown...")
seen_ids = set()
validation_errors = []

for i, q in enumerate(questions):
    q_id = q.get("id")
    q_md = q.get("question_markdown")

    # Validate ID uniqueness and presence
    if not q_id or not isinstance(q_id, str) or not q_id.strip():
        validation_errors.append(f"Row {i}: Missing, null, or empty 'id'.")
    elif q_id in seen_ids:
        validation_errors.append(f"Row {i}: Duplicate 'id' found -> {q_id}")
    else:
        seen_ids.add(q_id)

    # Validate question_markdown presence
    if not q_md or not isinstance(q_md, str) or not q_md.strip():
        validation_errors.append(f"Row {i} (ID: {q_id if q_id else 'UNKNOWN'}): Missing or empty 'question_markdown'.")

if validation_errors:
    print("\n❌ PRE-CHECK FAILED. Please fix the following issues in questions.json before tagging:")
    # Print up to 20 errors to avoid console flood
    for err in validation_errors[:20]:
        print(f"  - {err}")
    if len(validation_errors) > 20:
        print(f"  ... and {len(validation_errors) - 20} more errors.")
    sys.exit("Execution halted due to validation failures.")

print("✅ Pre-check passed! All questions have unique IDs and valid markdown content.")

# ==========================================
# 3. Dynamic Code Generation & Map Building
# ==========================================
CODE_TO_TOPIC = {}  # E.g., 'U1-S1-01' -> 'Exact Syllabus String'

def build_syllabus_taxonomy(data):
    """Parses syllabus.json into alphanumeric codes and builds reference text."""
    formatted_lines = []
    taxonomy = data.get("physics_syllabus_taxonomy", {})

    for paper_key, paper_val in taxonomy.items():
        for unit in paper_val.get("units", []):
            unit_code = str(unit.get("unit_code", "")).strip()
            unit_name = unit.get("unit_name", "").strip()
            formatted_lines.append(f"\n### [{unit_code}] {unit_name.upper()} ###")

            for section in unit.get("sections", []):
                sec_code = str(section.get("section_code", "")).strip()
                sec_name = section.get("section_name", "").strip()
                formatted_lines.append(f"\n-- {sec_code}: {sec_name} --")

                for idx, topic in enumerate(section.get("topics", [])):
                    seq_num = str(idx + 1).zfill(2)
                    topic_code = f"{unit_code}-{sec_code}-{seq_num}"

                    CODE_TO_TOPIC[topic_code] = topic.strip()
                    formatted_lines.append(f"[{topic_code}] {topic.strip()}")

    return "\n".join(formatted_lines)

OFFICIAL_SYLLABUS_REFERENCE = build_syllabus_taxonomy(syllabus_data)

print(f"Total questions loaded: {len(questions)}")
print(f"Total unique syllabus topic codes generated: {len(CODE_TO_TOPIC)}")

# ==========================================
# 4. Structured Output Schema
# ==========================================
class QuestionTopicMapping(BaseModel):
    index: int = Field(description="The batch index matching the input item")
    topic_codes: List[str] = Field(
        description="1 or 2 topic codes from the syllabus reference. The first MUST be the primary core concept."
    )

class BatchResponse(BaseModel):
    results: List[QuestionTopicMapping]

# ==========================================
# 5. Batch Processing Configuration
# ==========================================
def chunk_list(lst, n):
    for i in range(0, len(lst), n):
        yield lst[i:i + n]

all_batches = list(chunk_list(questions, BATCH_SIZE))
print(f"Total batches created: {len(all_batches)}")

target_batches_input = input("\nEnter batch numbers to run (e.g., '1, 3, 5') or leave blank for ALL: ")

if target_batches_input.strip():
    target_indices = [int(x.strip()) - 1 for x in target_batches_input.split(",") if x.strip().isdigit()]
    batches_to_run = [(idx, all_batches[idx]) for idx in target_indices if 0 <= idx < len(all_batches)]
    print(f"🎯 Targeting {len(batches_to_run)} specific batch(es).")
else:
    batches_to_run = list(enumerate(all_batches))
    print("🚀 Running all batches.")

# ==========================================
# 6. Core Mapping & Execution Logic
# ==========================================
failed_batches = []
permanently_failed_questions = []

SYSTEM_INSTRUCTION = f"""
You are an expert physics optional curriculum mapper for the UPSC Examination.
Your task is to map each exam question directly to its matching Official Syllabus Topic Codes.

CRITICAL RULES:
1. Return ONLY exact alphanumeric topic codes (e.g., 'U1-S1-01') from the Reference below. Never output topic text.
2. Code hierarchy:
   - Index 0 MUST be the Primary Topic (the direct core physics concept being tested).
   - Index 1 (Optional) ONLY if the question is genuinely hybrid/interdisciplinary and strictly requires a secondary concept. Do NOT add a secondary code if the primary covers it.
3. Keep results strictly within 1 to 2 codes maximum.
4. Prefer codes matching the question's 'unit' and 'section' metadata when applicable.

OFFICIAL SYLLABUS REFERENCE:
{OFFICIAL_SYLLABUS_REFERENCE}
"""

def process_batch(batch_data, batch_index):
    payload = []
    for i, q in enumerate(batch_data):
        raw_text = q.get("question_markdown", "")
        payload.append({
            "index": i,
            "id": q.get("id"),
            "unit": q.get("unit"),
            "section": q.get("section"),
            "text": str(raw_text)[:400]
        })

    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=f"Map the following questions to their official topic codes:\n{json.dumps(payload, ensure_ascii=False)}",
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            response_mime_type="application/json",
            response_schema=BatchResponse,
            temperature=0.0
        )
    )

    parsed_obj = json.loads(response.text)
    results = parsed_obj.get("results", [])
    res_by_idx = {r["index"]: r.get("topic_codes", []) for r in results if "index" in r}

    # Deterministic Python translation to syllabus topic names
    for i, q in enumerate(batch_data):
        q_id = q.get("id", f"B{batch_index+1}_Idx{i}")
        if i not in res_by_idx:
            permanently_failed_questions.append({
                "id": q_id,
                "error": "Missing from Gemini response"
            })
            continue

        raw_codes = res_by_idx[i]
        resolved_topics = []

        for code in raw_codes[:2]:
            clean_code = str(code).strip().upper()
            if clean_code in CODE_TO_TOPIC:
                topic_str = CODE_TO_TOPIC[clean_code]
                if topic_str not in resolved_topics:
                    resolved_topics.append(topic_str)
            else:
                print(f"⚠️ Warning: Non-existent syllabus code '{clean_code}' skipped for Question ID {q_id}")

        if resolved_topics:
            q["syllabus_topic"] = resolved_topics
        else:
            permanently_failed_questions.append({
                "id": q_id,
                "error": "No valid syllabus codes produced",
                "raw_codes": raw_codes
            })

# --- Execution Pass ---
for original_idx, batch in batches_to_run:
    display_num = original_idx + 1
    try:
        process_batch(batch, original_idx)
        print(f"✅ Processed batch {display_num}/{len(all_batches)}")
        time.sleep(2)
    except Exception as e:
        print(f"⚠️ Batch {display_num} failed: {e}. Queued for retry.")
        failed_batches.append((original_idx, batch))
        time.sleep(5)

# --- Retry Failed Batches ---
if failed_batches:
    print(f"\n🔄 Retrying {len(failed_batches)} failed batch(es)...")
    for original_idx, batch in failed_batches:
        display_num = original_idx + 1
        try:
            process_batch(batch, original_idx)
            print(f"✅ Retry succeeded for batch {display_num}")
            time.sleep(2)
        except Exception as e:
            print(f"❌ Retry failed for batch {display_num}: {e}")
            for q in batch:
                permanently_failed_questions.append({
                    "id": q.get("id"),
                    "error": f"Batch exception: {str(e)}"
                })

# ==========================================
# 7. Save & Download Output
# ==========================================
if target_batches_input.strip():
    for original_idx, processed_batch in batches_to_run:
        all_batches[original_idx] = processed_batch

final_questions = [q for batch in all_batches for q in batch]

with open(OUTPUT_JSON, "w", encoding="utf-8") as out:
    json.dump(final_questions, out, indent=2, ensure_ascii=False)

print(f"\n🎉 Finished! Output saved as '{OUTPUT_JSON}'")
files.download(OUTPUT_JSON)

if permanently_failed_questions:
    with open(FAILED_QUESTIONS_JSON, "w", encoding="utf-8") as f:
        json.dump(permanently_failed_questions, f, indent=2, ensure_ascii=False)
    print(f"⚠️ {len(permanently_failed_questions)} questions encountered issues. Saved to '{FAILED_QUESTIONS_JSON}'")
    files.download(FAILED_QUESTIONS_JSON)