# -*- coding: utf-8 -*-
"""PYQ Repository Processor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvQgDtGKRL8z_rWA8AboTJklEptQPdRe
"""

import os
import json
import re
import shutil
import uuid
from google.colab import files
import zipfile

def extract_and_setup():
    print("📂 Please upload your ZIP file containing 'questions.json', 'syllabus.json', and the 'images/' folder.")
    uploaded = files.upload()

    if not uploaded:
        raise ValueError("No file uploaded. Please run the cell again.")

    zip_filename = list(uploaded.keys())[0]
    extract_dir = "working_dir"

    # Cleanup previous runs
    if os.path.exists(extract_dir):
        shutil.rmtree(extract_dir)
    os.makedirs(extract_dir)

    # Extract
    with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
        zip_ref.extractall(extract_dir)

    print(f"✅ Extracted {zip_filename} successfully.")
    return extract_dir

def build_taxonomy_map(syllabus_path):
    with open(syllabus_path, "r", encoding="utf-8") as f:
        syllabus = json.load(f)

    topic_map = {}
    taxonomy = syllabus.get("physics_syllabus_taxonomy", {})

    for paper_key, paper_val in taxonomy.items():
        for unit in paper_val.get("units", []):
            u_code = unit.get("unit_code")
            u_name = unit.get("unit_name")
            for section in unit.get("sections", []):
                s_code = section.get("section_code")
                s_name = section.get("section_name")
                for topic in section.get("topics", []):
                    normalized_topic = str(topic).strip().lower()
                    topic_map[normalized_topic] = {
                        "unit_code": u_code,
                        "unit_name": u_name,
                        "section_code": s_code,
                        "section_name": s_name,
                        "canonical_topic": topic
                    }
    return topic_map

def parse_old_id(old_id):
    if not old_id:
        return "UNKNOWN", 0, 999
    # Pattern: PH-U1-S1-CSE2018-01
    match = re.match(r'PH-U\d+-S\d+-([A-Za-z]+)(\d{4})-(\d+)', str(old_id))
    if match:
        return match.group(1), int(match.group(2)), int(match.group(3))
    # Safe Fallback to prevent TypeError during chronological sorting
    return "UNKNOWN", 0, 999

def pre_run_verification(questions, images_dir, topic_map):
    """
    Validates all constraints before executing reassignment logic.
    Returns (discrepancies_list, id_was_updated, updated_questions)
    """
    discrepancies = []
    id_updated = False

    for q in questions:
        q_id = q.get("id")
        original_id = q.get("original_id", q_id)
        q_discrepancy = {"question_id": q_id, "errors": []}

        # 0. Check ID presence
        if not q_id or str(q_id).strip() == "":
            new_hash_id = f"TEMP-{uuid.uuid4().hex[:8].upper()}"
            q["id"] = new_hash_id
            q["original_id"] = original_id if original_id else new_hash_id
            q_discrepancy["question_id"] = new_hash_id
            q_discrepancy["errors"].append("Missing ID. Assigned temporary hash ID.")
            id_updated = True

        # 1. Check for empty question or empty topics array
        q_text = q.get("question_markdown", "") or q.get("Question_metadata", "")
        if not q_text or str(q_text).strip() == "":
            q_discrepancy["errors"].append("Question text/metadata is totally empty.")

        topics = q.get("syllabus_topic", [])
        if not topics or len(topics) == 0:
            q_discrepancy["errors"].append("Syllabus topics array is empty.")
        else:
            # 1b. Check if ALL topics strictly match syllabus dictionary
            for topic in topics:
                if str(topic).strip().lower() not in topic_map:
                    q_discrepancy["errors"].append(f"Topic '{topic}' does not strictly match any official syllabus topic.")

        # 2. Check Image integrity
        img_array = q.get("images", [])

        # 2a. Find all image-like filenames physically mentioned in the text
        found_in_text = re.findall(r'[\w\-\.]+\.(?:png|jpe?g|gif)', str(q_text), re.IGNORECASE)
        for img_in_text in found_in_text:
            if img_in_text not in img_array:
                q_discrepancy["errors"].append(f"Image '{img_in_text}' is mentioned in text but missing from 'images' JSON array.")

        # 2b. Check if all items in images array exist physically in the folder
        for img_name in img_array:
            if not images_dir:
                q_discrepancy["errors"].append(f"Image file '{img_name}' is listed in JSON, but no 'images' folder exists in the uploaded ZIP.")
                continue

            img_path = os.path.join(images_dir, img_name)
            if not os.path.exists(img_path):
                q_discrepancy["errors"].append(f"Image file '{img_name}' is missing from the physical 'images' folder.")

        # Append to master log if issues exist
        if q_discrepancy["errors"]:
            discrepancies.append(q_discrepancy)

    return discrepancies, id_updated, questions

def process_repository():
    extract_dir = extract_and_setup()

    # File Paths
    questions_path = None
    syllabus_path = None
    images_dir = None

    # Locate files dynamically inside the extracted folder
    for root, dirs, files_list in os.walk(extract_dir):
        if "questions.json" in files_list:
            questions_path = os.path.join(root, "questions.json")
        if "syllabus.json" in files_list:
            syllabus_path = os.path.join(root, "syllabus.json")
        if "images" in dirs:
            images_dir = os.path.join(root, "images")

    if not questions_path or not syllabus_path:
        raise FileNotFoundError("Could not find 'questions.json' or 'syllabus.json' in the uploaded zip.")

    topic_map = build_taxonomy_map(syllabus_path)

    with open(questions_path, "r", encoding="utf-8") as f:
        questions = json.load(f)

    print("\n🔎 Running Pre-Run Verification Phase...")
    discrepancies, id_updated, questions = pre_run_verification(questions, images_dir, topic_map)

    if discrepancies:
        print(f"⚠️ Verification Failed! Found {len(discrepancies)} questions with discrepancies.")
        error_out_dir = "verification_failures"
        if os.path.exists(error_out_dir): shutil.rmtree(error_out_dir)
        os.makedirs(error_out_dir)

        # Save the discrepancy log
        with open(os.path.join(error_out_dir, "verification_errors.json"), "w", encoding="utf-8") as f:
            json.dump(discrepancies, f, indent=2, ensure_ascii=False)

        # Output the modified JSON if hash IDs were injected
        if id_updated:
            with open(os.path.join(error_out_dir, "temporaryid_questions.json"), "w", encoding="utf-8") as f:
                json.dump(questions, f, indent=2, ensure_ascii=False)
            print("📝 Missing IDs were found. Exporting 'temporaryid_questions.json'")

        # Zip and return the error data
        error_zip = "verification_failed_logs.zip"
        with zipfile.ZipFile(error_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
            for root, dirs, files_list in os.walk(error_out_dir):
                for file in files_list:
                    file_path = os.path.join(root, file)
                    zipf.write(file_path, os.path.relpath(file_path, error_out_dir))

        print("⛔ Halting processing. Downloading verification logs...")
        files.download(error_zip)
        return # STOP execution here.

    print("✅ Pre-Run Verification Passed! Proceeding with Taxonomy mapping...")

    # --- MAIN EXECUTION LOGIC CONTINUES ---
    section_changes_log = []
    unit_section_changes_log = []
    image_correction_log = []
    error_log = []
    processed_items = []

    # --- STEP 1: Analyze and Map New Taxonomy ---
    for q in questions:
        current_id = q.get("id", "")
        original_id = q.get("original_id", current_id)
        topics = q.get("syllabus_topic", [])

        exam, year, old_serial = parse_old_id(current_id)
        primary_topic = topics[0]
        taxonomy_info = topic_map.get(str(primary_topic).strip().lower())

        if not taxonomy_info:
            # Should theoretically be caught by pre-run verification, but keeping as a safety net.
            error_log.append({
                "original_id": original_id,
                "current_id": current_id,
                "reason": f"CRITICAL: Topic '{primary_topic}' bypassed validation but isn't in topic map."
            })
            processed_items.append({"q": q, "skip": True, "sort_key": ("Z", "Z", -9999, "Z", 999)})
            continue

        if exam == "UNKNOWN" or year == 0:
            error_log.append({
                "original_id": original_id,
                "current_id": current_id,
                "reason": f"Format error: Could not parse Exam/Year from ID '{current_id}'. Chronological sorting will fail for this item."
            })
            processed_items.append({"q": q, "skip": True, "sort_key": ("Z", "Z", -9999, "Z", 999)})
            continue

        item = {
            "q": q,
            "skip": False,
            "original_id": original_id,
            "old_id": current_id,
            "exam": exam,
            "year": year,
            "old_serial": old_serial,
            "new_unit_code": taxonomy_info["unit_code"],
            "new_unit_name": taxonomy_info["unit_name"],
            "new_section_code": taxonomy_info["section_code"],
            "new_section_name": taxonomy_info["section_name"]
        }

        # Chronological Sort Hierarchy
        item["sort_key"] = (
            item["new_unit_code"],
            item["new_section_code"],
            -item["year"],
            item["exam"],
            item["old_serial"]
        )
        processed_items.append(item)

    # --- STEP 2: Sort chronologically, Assign IDs, and Enforce Image Naming ---
    processed_items.sort(key=lambda x: x["sort_key"])

    current_prefix = ""
    counter = 1
    image_rename_queue = []
    final_questions = []

    for item in processed_items:
        q = item["q"]
        if item["skip"]:
            final_questions.append(q)
            continue

        prefix = f"PH-{item['new_unit_code']}-{item['new_section_code']}-{item['exam']}{item['year']}"

        if prefix == current_prefix:
            counter += 1
        else:
            current_prefix = prefix
            counter = 1

        new_id = f"{prefix}-{counter:02d}"
        old_id = item["old_id"]
        original_id = item["original_id"]

        # 🚨 FIX: Extract old values BEFORE updating JSON properties
        old_unit = q.get("unit", "N/A")
        old_section = q.get("section", "N/A")

        changed_unit = (item["new_unit_name"] != old_unit)
        changed_section = (item["new_section_name"] != old_section)
        id_changed = (new_id != old_id)

        # Generate the reason for image/ID corrections for verbose logging
        id_change_reason = "No ID Change"
        if id_changed:
            if changed_unit:
                id_change_reason = f"Unit reassignment ({old_unit} ➔ {item['new_unit_name']}) forced an ID update."
            elif changed_section:
                id_change_reason = f"Section reassignment ({old_section} ➔ {item['new_section_name']}) forced an ID update."
            else:
                id_change_reason = f"Chronological/Sequence ID conflict resolution forced an update."

        new_images_list = []
        markdown = q.get("question_markdown", "")
        metadata = q.get("Question_metadata", "")
        images_corrected = False

        for idx, old_img in enumerate(q.get("images", [])):
            ext = os.path.splitext(old_img)[1]
            expected_img_name = f"{new_id}_img_{idx+1}{ext}"
            new_images_list.append(expected_img_name)

            if old_img != expected_img_name:
                images_corrected = True
                if images_dir:
                    old_path = os.path.join(images_dir, old_img)
                    new_path = os.path.join(images_dir, expected_img_name)
                    if os.path.exists(old_path):
                        image_rename_queue.append((old_path, new_path))

                if markdown:
                    markdown = markdown.replace(old_img, expected_img_name)
                if metadata:
                    metadata = metadata.replace(old_img, expected_img_name)

        # APPLY modifications to JSON Dictionary
        q["id"] = new_id
        q["unit"] = item["new_unit_name"]
        q["section"] = item["new_section_name"]
        q["images"] = new_images_list
        if markdown: q["question_markdown"] = markdown
        if metadata: q["Question_metadata"] = metadata

        # Generate Logs
        log_entry = {
            "original_id": original_id,
            "old_id": old_id if id_changed else None,
            "current_id": new_id,
            "topic_triggered": q.get("syllabus_topic")[0]
        }

        if changed_unit:
            log_entry["old_unit"] = old_unit
            log_entry["new_unit"] = item["new_unit_name"]
            log_entry["old_section"] = old_section
            log_entry["new_section"] = item["new_section_name"]
            log_entry["reason"] = f"Unit updated to match Primary Topic '{log_entry['topic_triggered']}'"
            unit_section_changes_log.append(log_entry)
        elif changed_section:
            log_entry["old_section"] = old_section
            log_entry["new_section"] = item["new_section_name"]
            log_entry["reason"] = f"Section updated to match Primary Topic '{log_entry['topic_triggered']}'"
            section_changes_log.append(log_entry)

        if images_corrected:
            image_correction_log.append({
                "original_id": original_id,
                "old_id": old_id if id_changed else None,
                "current_id": new_id,
                "reason": id_change_reason
            })

        final_questions.append(q)

    # --- STEP 3: Secure Two-Pass Image Renaming ---
    # UUIDs prevent A->B and B->C overwrite cycles (Conflict Resolution)
    if image_rename_queue:
        print(f"🔄 Processing {len(image_rename_queue)} image file renames...")
        temp_rename_queue = []
        for old_path, new_path in image_rename_queue:
            if old_path == new_path: continue
            temp_path = os.path.join(os.path.dirname(old_path), f"temp_{uuid.uuid4().hex}.jpeg")
            os.rename(old_path, temp_path)
            temp_rename_queue.append((temp_path, new_path))

        for temp_path, new_path in temp_rename_queue:
            os.rename(temp_path, new_path)

    # --- STEP 4: Save Outputs ---
    out_dir = "updated_output"
    if os.path.exists(out_dir): shutil.rmtree(out_dir)
    os.makedirs(out_dir)

    with open(os.path.join(out_dir, "questions.json"), "w", encoding="utf-8") as f:
        json.dump(final_questions, f, indent=2, ensure_ascii=False)

    with open(os.path.join(out_dir, "log_section_changes.json"), "w", encoding="utf-8") as f:
        json.dump(section_changes_log, f, indent=2, ensure_ascii=False)

    with open(os.path.join(out_dir, "log_unit_changes.json"), "w", encoding="utf-8") as f:
        json.dump(unit_section_changes_log, f, indent=2, ensure_ascii=False)

    with open(os.path.join(out_dir, "log_image_corrections.json"), "w", encoding="utf-8") as f:
        json.dump(image_correction_log, f, indent=2, ensure_ascii=False)

    with open(os.path.join(out_dir, "log_errors.json"), "w", encoding="utf-8") as f:
        json.dump(error_log, f, indent=2, ensure_ascii=False)

    if images_dir and os.path.exists(images_dir):
        shutil.move(images_dir, os.path.join(out_dir, "images"))

    # --- STEP 5: Zip and Download ---
    output_zip = "updated_repository.zip"
    with zipfile.ZipFile(output_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files_list in os.walk(out_dir):
            for file in files_list:
                file_path = os.path.join(root, file)
                arcname = os.path.relpath(file_path, out_dir)
                zipf.write(file_path, arcname)

    print("\n🎉 Deployment Processing Complete!")
    print(f"📊 Summary:")
    print(f"  - Total Questions Validated: {len(final_questions)}")
    print(f"  - Unit & Section Updates: {len(unit_section_changes_log)}")
    print(f"  - Section-Only Updates: {len(section_changes_log)}")
    print(f"  - Image Mismatches Corrected: {len(image_rename_queue)} files")
    print(f"  - Unhandled/Errors: {len(error_log)}")

    files.download(output_zip)

# Execute the main function
process_repository()