# -*- coding: utf-8 -*-
"""PYQ JSON Cleaner.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zaCb3aI2E8-R3puBo2EgjA-K9YGlsTm9
"""

import os
import json
import re
import time
import shutil
import random
import string
import getpass
import zipfile
from typing import List
from pydantic import BaseModel, Field
from google.colab import files
from google import genai
from google.genai import types

# ==========================================
# INITIALIZATION
# ==========================================
print("🔑 Initialize Gemini Client")
api_key = getpass.getpass("Enter your Gemini API Key: ")
client = genai.Client(api_key=api_key)
GEMINI_MODEL = "gemini-3.5-flash-lite"

print("\n📂 Upload your ZIP file ('questions.json', 'syllabus.json', 'images/' folder)")
uploaded = files.upload()
if not uploaded:
    raise ValueError("No file uploaded.")

zip_filename = list(uploaded.keys())[0]
WORK_DIR = "working_dir"
OUT_DIR = "processed_output"

for d in [WORK_DIR, OUT_DIR]:
    if os.path.exists(d): shutil.rmtree(d)
os.makedirs(WORK_DIR)
os.makedirs(OUT_DIR)

with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
    zip_ref.extractall(WORK_DIR)

questions_path, images_dir = None, None
for root, dirs, files_list in os.walk(WORK_DIR):
    if "questions.json" in files_list: questions_path = os.path.join(root, "questions.json")
    if "images" in dirs: images_dir = os.path.join(root, "images")

if not questions_path:
    raise FileNotFoundError("Missing questions.json in ZIP.")

with open(questions_path, "r", encoding="utf-8") as f:
    questions = json.load(f)

error_logs = []
split_logs = []
failed_batch_logs = []

def generate_short_id():
    return "q_" + ''.join(random.choices(string.ascii_lowercase + string.digits, k=8))

def chunk_list(lst, n):
    for i in range(0, len(lst), n): yield lst[i:i + n]

def log_error(q_id, orig_id, step, error_msg):
    error_logs.append({
        "id": q_id,
        "original_id": orig_id,
        "step": step,
        "error": error_msg
    })

# ==========================================
# STEP 0: SCHEMA CORRECTION
# ==========================================
print("\n⚙️ STEP 0: Applying Schema Corrections...")
DEFAULT_SCHEMA = {
    "id": "", "display_id": "UNKNOWN", "exam": "UNKNOWN", "year": 0,
    "marks": "", "images": [], "has_diagram": False,
    "question_markdown": "", "unit": "UNKNOWN", "section": "UNKNOWN",
    "syllabus_topic": [], "original_id": ""
}

for i, q in enumerate(questions):
    for key, default_val in DEFAULT_SCHEMA.items():
        if key not in q:
            q[key] = default_val

# ==========================================
# STEP 1: ID ASSIGNMENT & IMAGE RENAMING
# ==========================================
print("🏷️ STEP 1: Generating Unique IDs and Renaming Images...")
used_ids = set()
out_images_dir = os.path.join(OUT_DIR, "images")
os.makedirs(out_images_dir, exist_ok=True)

for q in questions:
    old_id = q.get("id", "")
    orig_id = q.get("original_id", "UNKNOWN")

    if not re.match(r"^q_[a-z0-9]{8}$", old_id) or old_id in used_ids:
        while True:
            new_id = generate_short_id()
            if new_id not in used_ids: break
        q["id"] = new_id
    else:
        new_id = old_id

    used_ids.add(new_id)

    old_images = q.get("images", [])
    new_images = []
    markdown = q.get("question_markdown", "")

    for idx, old_img in enumerate(old_images):
        ext = os.path.splitext(old_img)[1] or ".jpeg"
        new_img = f"{new_id}_img_{idx+1}{ext}"
        new_images.append(new_img)

        if images_dir:
            old_path = os.path.join(images_dir, old_img)
            new_path = os.path.join(out_images_dir, new_img)
            if os.path.exists(old_path):
                shutil.copy2(old_path, new_path)
            else:
                log_error(new_id, orig_id, "Image Rename", f"Missing physical image: {old_img}")

        markdown = markdown.replace(old_img, new_img)

    q["images"] = new_images
    q["question_markdown"] = markdown
    q["has_diagram"] = len(new_images) > 0

intermediate_path = os.path.join(OUT_DIR, "id_assigned_questions.json")
with open(intermediate_path, "w", encoding="utf-8") as f:
    json.dump(questions, f, indent=2, ensure_ascii=False)
print("   ✅ Saved 'id_assigned_questions.json' as safe checkpoint.")

# ==========================================
# STEP 2: BATCH QUESTION SPLITTING (LLM)
# ==========================================
print("\n✂️ STEP 2: Detecting and Splitting Merged Questions...")

class SplitQuestionItem(BaseModel):
    question_markdown: str
    exam: str
    year: int
    marks: str
    original_id: str
    images: List[str]

class SplitDecision(BaseModel):
    id: str = Field(description="The ID of the evaluated question.")
    is_merged: bool = Field(description="True ONLY if the text contains completely disjointed questions accidentally merged.")
    reason: str = Field(description="Detailed reason for why the question was split or kept whole.")
    split_items: List[SplitQuestionItem] = Field(description="Separated questions. Empty if is_merged is false.")

class BatchSplitResponse(BaseModel):
    evaluations: List[SplitDecision]

SPLIT_PROMPT = """
Evaluate the provided batch of exam questions.
- APPLY STRICT SPLITTING CRITERIA: ONLY split a question if the parts belong to completely different, unrelated topics OR if multiple distinct numbered questions (e.g., Q5 and Q6) were accidentally concatenated.
- DO NOT SPLIT if a question contains a theoretical derivation and an associated numerical problem. These are practically part of the same unified question.
- DO NOT SPLIT if multiple sub-questions share a common preliminary context paragraph, reading passage, or data table.
- DO NOT SPLIT if the sub-questions share a common diagram/image. If both parts refer to the same visual, they must remain merged.
- IF they are just sub-parts (e.g., (i) and (ii)) of one unified question number, DO NOT SPLIT (is_merged=false).
- INHERITANCE RULE: If a split daughter question does not have its own distinct exam, year, marks, or original_id visibly stated in the text, you MUST output the parent's original exam, year, marks, and original_id for that daughter question.
- Always provide a clear 'reason' for your decision.
"""

split_candidates = [q for q in questions if "\n\n" in q.get("question_markdown", "") and len(q.get("question_markdown", "")) > 150]
split_batches = list(chunk_list(split_candidates, 20))
print(f"   🔍 Found {len(split_candidates)} potential merged questions to evaluate.")
print(f"   📦 Total splitting batches created: {len(split_batches)}")

target_batches_input = input("\nEnter specific batch numbers to process for SPLITTING (comma-separated, e.g., '1, 3, 5') or leave blank to process ALL: ")

if target_batches_input.strip():
    target_indices = [int(x.strip()) - 1 for x in target_batches_input.split(",") if x.strip().isdigit()]
    batches_to_run = [(idx, split_batches[idx]) for idx in target_indices if 0 <= idx < len(split_batches)]
    print(f"🎯 Targeting {len(batches_to_run)} specific batch(es).")
else:
    batches_to_run = list(enumerate(split_batches))
    print("🚀 Running all splitting batches.")

questions_dict = {q["id"]: q for q in questions}
failed_split_batches = []

def process_split_batch(batch, b_idx, is_retry=False):
    payload = [{"id": q["id"], "original_id": q.get("original_id", ""), "text": q["question_markdown"]} for q in batch]
    response = client.models.generate_content(
        model=GEMINI_MODEL,
        contents=f"Batch evaluation:\n{json.dumps(payload, ensure_ascii=False)}",
        config=types.GenerateContentConfig(
            system_instruction=SPLIT_PROMPT,
            response_mime_type="application/json",
            response_schema=BatchSplitResponse,
            temperature=0.0
        )
    )
    time.sleep(2) # 15 RPM Rate Limit Enforcement

    evaluations = json.loads(response.text).get("evaluations", [])
    ev_by_id = {ev["id"]: ev for ev in evaluations}

    if not is_retry and len(ev_by_id) != len(batch):
        raise ValueError(f"Batch response missing items. Expected {len(batch)}, got {len(ev_by_id)}")

    for q in batch:
        q_id = q["id"]
        q_orig_id = q.get("original_id", "UNKNOWN")

        if q_id not in ev_by_id:
            if is_retry:
                log_error(q_id, q_orig_id, "Splitting Retry", "Missing from Gemini response on retry.")
            continue

        ev = ev_by_id[q_id]

        if ev.get("is_merged") and ev.get("split_items"):

            # --- VALIDATION: Check for shared diagrams across daughters ---
            shared_images_found = False
            all_assigned_images = set()
            for sq in ev["split_items"]:
                for img in sq.get("images", []):
                    if img in all_assigned_images:
                        shared_images_found = True
                        break
                    all_assigned_images.add(img)
                if shared_images_found:
                    break

            if shared_images_found:
                print(f"   🚫 Split rejected for {q_id}: Daughter questions incorrectly share common diagrams.")
                continue # Abort split for this specific question

            print(f"   ✂️ Split applied to {q_id} (Orig ID: {q_orig_id})")

            if q_id in questions_dict:
                orig_q = questions_dict.pop(q_id)
                daughter_ids = []

                for index, sq in enumerate(ev["split_items"]):
                    new_q = orig_q.copy()

                    # Force Python-level inheritance
                    if not sq.get("exam") or sq.get("exam") == "UNKNOWN": sq["exam"] = orig_q.get("exam")
                    if not sq.get("year") or sq.get("year") == 0: sq["year"] = orig_q.get("year")
                    if not sq.get("marks"): sq["marks"] = orig_q.get("marks")
                    new_q["original_id"] = orig_q.get("original_id")

                    new_q.update(sq)

                    # ID Logic: First daughter keeps parent ID, subsequent get new ID
                    if index == 0:
                        assigned_id = q_id
                    else:
                        while True:
                            assigned_id = generate_short_id()
                            if assigned_id not in used_ids: break
                        used_ids.add(assigned_id)

                    new_q["id"] = assigned_id

                    # --- IMAGE RENAMING: Move files exclusively to the new daughter ---
                    if index > 0 and new_q.get("images"):
                        updated_images = []
                        current_markdown = new_q.get("question_markdown", "")

                        for img_idx, old_img_name in enumerate(new_q["images"]):
                            ext = os.path.splitext(old_img_name)[1] or ".jpeg"
                            new_img_name = f"{assigned_id}_img_{img_idx+1}{ext}"

                            # Rename on filesystem (Move since mutual exclusivity is confirmed)
                            old_img_path = os.path.join(out_images_dir, old_img_name)
                            new_img_path = os.path.join(out_images_dir, new_img_name)

                            if os.path.exists(old_img_path):
                                shutil.move(old_img_path, new_img_path)
                            else:
                                log_error(assigned_id, orig_q.get("original_id"), "Split Image Rename", f"Missing image during split: {old_img_name}")

                            # Update markdown & list
                            current_markdown = current_markdown.replace(old_img_name, new_img_name)
                            updated_images.append(new_img_name)

                        new_q["images"] = updated_images
                        new_q["question_markdown"] = current_markdown

                    questions_dict[assigned_id] = new_q
                    daughter_ids.append(assigned_id)

                # Log the split
                split_logs.append({
                    "parent_id": q_id,
                    "parent_original_id": q_orig_id,
                    "original_markdown": orig_q.get("question_markdown"),
                    "reason": ev.get("reason", "No reason provided by LLM"),
                    "daughter_ids": daughter_ids
                })

# --- Split Pass 1 ---
for original_idx, batch in batches_to_run:
    display_num = original_idx + 1
    try:
        process_split_batch(batch, original_idx, is_retry=False)
        print(f"   ✅ Processed Split Batch {display_num}")
    except Exception as e:
        print(f"   ⚠️ Error on Split Batch {display_num}. Exception: {str(e)}. Queued for retry.")
        failed_split_batches.append((original_idx, batch))
        time.sleep(5)

# --- Split Pass 2 (Retry) ---
if failed_split_batches:
    print(f"\n🔄 Retrying {len(failed_split_batches)} failed split batches (per-question fault tolerance)...")
    for original_idx, batch in failed_split_batches:
        display_num = original_idx + 1
        try:
            process_split_batch(batch, original_idx, is_retry=True)
            print(f"   ✅ Retry successful for Split Batch {display_num}")
        except Exception as e:
            err_msg = str(e)
            print(f"   ❌ Complete Failure on Split Batch {display_num}. Exception: {err_msg}")
            failed_batch_logs.append({
                "batch_number": display_num,
                "step": "Question Splitting Pass 2",
                "error": err_msg,
                "batch_question_ids": [q["id"] for q in batch]
            })

# ==========================================
# FINALIZATION & PACKAGING
# ==========================================
print("\n📦 Packaging final zip file...")

final_questions = list(questions_dict.values())
with open(os.path.join(OUT_DIR, "questions.json"), "w", encoding="utf-8") as f:
    json.dump(final_questions, f, indent=2, ensure_ascii=False)

if error_logs:
    with open(os.path.join(OUT_DIR, "error_logs.json"), "w", encoding="utf-8") as f:
        json.dump(error_logs, f, indent=2, ensure_ascii=False)

if split_logs:
    with open(os.path.join(OUT_DIR, "split_history_logs.json"), "w", encoding="utf-8") as f:
        json.dump(split_logs, f, indent=2, ensure_ascii=False)

if failed_batch_logs:
    with open(os.path.join(OUT_DIR, "failed_batches.json"), "w", encoding="utf-8") as f:
        json.dump(failed_batch_logs, f, indent=2, ensure_ascii=False)

output_zip = "cleaned_questions_repository.zip"
with zipfile.ZipFile(output_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for root, dirs, files_list in os.walk(OUT_DIR):
        for file in files_list:
            file_path = os.path.join(root, file)
            zipf.write(file_path, os.path.relpath(file_path, OUT_DIR))

print(f"\n🎉 Process Complete! Valid questions: {len(final_questions)}")
print(f"   - Questions split: {len(split_logs)}")
print(f"   - Errors logged: {len(error_logs)}")
print(f"   - Failed batches: {len(failed_batch_logs)}")
files.download(output_zip)