# -*- coding: utf-8 -*-
"""PYQ Repository Processor.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvQgDtGKRL8z_rWA8AboTJklEptQPdRe
"""

import os
import json
import re
import shutil
import zipfile
from collections import defaultdict
from google.colab import files

def extract_and_setup():
    print("📂 Step 1: Please upload your ZIP file ('questions.json', 'syllabus.json', 'images/' folder)")
    uploaded = files.upload()

    if not uploaded:
        raise ValueError("No file uploaded. Execution halted.")

    zip_filename = list(uploaded.keys())[0]
    work_dir = "working_dir"

    if os.path.exists(work_dir): shutil.rmtree(work_dir)
    os.makedirs(work_dir)

    with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
        zip_ref.extractall(work_dir)

    print(f"   ✅ Extracted {zip_filename} successfully.")
    return work_dir

def build_taxonomy_map(syllabus_path):
    print("🗺️ Step 2: Building Syllabus Taxonomy Map for Sorting...")
    with open(syllabus_path, "r", encoding="utf-8") as f:
        syllabus = json.load(f)

    topic_map = {}
    taxonomy = syllabus.get("physics_syllabus_taxonomy", {})

    unit_order, section_order, topic_order = 0, 0, 0

    for paper_key, paper_val in taxonomy.items():
        for unit in paper_val.get("units", []):
            unit_order += 1
            u_code = unit.get("unit_code", "").strip()
            u_name = unit.get("unit_name", "").strip()

            for section in unit.get("sections", []):
                section_order += 1
                s_code = section.get("section_code", "").strip()
                s_name = section.get("section_name", "").strip()

                for topic in section.get("topics", []):
                    topic_order += 1
                    normalized_topic = str(topic).strip().lower()
                    topic_map[normalized_topic] = {
                        "unit_code": u_code,
                        "unit_name": u_name,
                        "section_code": s_code,
                        "section_name": s_name,
                        "canonical_topic": topic.strip(),
                        "u_idx": unit_order,
                        "s_idx": section_order,
                        "t_idx": topic_order
                    }
    print(f"   ✅ Mapped {len(topic_map)} unique syllabus topics with hierarchical indices.")
    return topic_map

def pre_verification(questions, images_dir):
    print("\n🔍 Step 3: Running Strict Pre-Verification Checks...")
    errors = []
    seen_ids = set()

    for i, q in enumerate(questions):
        q_id = q.get("id")
        q_errors = []

        # 1. Unique Alphanumeric ID Check
        if not q_id or not str(q_id).strip():
            q_errors.append("Missing or empty 'id'.")
        else:
            if not re.match(r"^[a-zA-Z0-9_]+$", str(q_id)):
                q_errors.append(f"ID '{q_id}' is not strictly alphanumeric/underscore.")
            if q_id in seen_ids:
                q_errors.append(f"Duplicate ID found: '{q_id}'.")
            seen_ids.add(q_id)

        # 2. Non-empty Metadata/Markdown Check
        q_md = q.get("question_markdown", "")
        q_meta = q.get("question_metadata", "")
        if not str(q_md).strip() and not str(q_meta).strip():
            q_errors.append("Both 'question_markdown' and 'question_metadata' are totally empty.")

        # 3. Non-empty Topic Check
        topics = q.get("syllabus_topic", [])
        if not topics or not isinstance(topics, list) or len(topics) == 0:
            q_errors.append("Missing or empty 'syllabus_topic' array.")
        elif not str(topics[0]).strip():
            q_errors.append("Primary syllabus topic is an empty string.")

        # 4. Image Consistency Check
        img_array = q.get("images", [])
        combined_text = str(q_md) + " " + str(q_meta)
        found_in_text = re.findall(r'[\w\-\.]+\.(?:png|jpe?g|gif)', combined_text, re.IGNORECASE)

        # Array vs Text
        for img_in_text in found_in_text:
            if img_in_text not in img_array:
                q_errors.append(f"Image '{img_in_text}' is in text but missing from 'images' array.")

        # Array vs Physical Folder
        for img_name in img_array:
            if not images_dir or not os.path.exists(os.path.join(images_dir, img_name)):
                q_errors.append(f"Image '{img_name}' is in array but missing from physical images folder.")

        if q_errors:
            errors.append({"id": q_id if q_id else f"Row {i}", "errors": q_errors})

    if errors:
        print(f"   ❌ Pre-verification FAILED. Found discrepancies in {len(errors)} questions.")
        for e in errors[:5]:
            print(f"      - ID {e['id']}: {', '.join(e['errors'])}")
        if len(errors) > 5: print(f"      ... and {len(errors) - 5} more.")
    else:
        print("   ✅ All pre-verification checks passed successfully.")

    return errors

def assign_and_sort(questions, topic_map):
    print("\n⚙️ Step 4: Assigning Taxonomy and Sorting...")
    processed_items = []
    unmapped_errors = []

    for q in questions:
        q_id = q.get("id")
        exam = str(q.get("exam", "UNKNOWN")).strip().upper()

        # Ensure year is integer for sorting
        try:
            year = int(q.get("year", 0))
        except ValueError:
            year = 0

        # Taxonomy Mapping
        primary_topic = str(q.get("syllabus_topic", [""])[0]).strip().lower()
        taxonomy_info = topic_map.get(primary_topic)

        if not taxonomy_info:
            unmapped_errors.append({"id": q_id, "topic": primary_topic, "error": "Primary topic not found in Syllabus Map."})
            continue

        # Update Unit and Section directly
        q["unit"] = taxonomy_info["unit_name"]
        q["section"] = taxonomy_info["section_name"]

        # 1. Year (descending) -> 2. Exam (CSE first) -> 3. Unit -> 4. Section -> 5. Topic
        exam_rank = 0 if exam == "CSE" else 1 if exam == "IFOS" else 2
        sort_key = (
            -year,
            exam_rank,
            taxonomy_info["u_idx"],
            taxonomy_info["s_idx"],
            taxonomy_info["t_idx"]
        )

        processed_items.append({
            "q": q,
            "sort_key": sort_key,
            "u_code": taxonomy_info["unit_code"],
            "s_code": taxonomy_info["section_code"],
            "exam": exam,
            "year": year
        })

    # Sort the list based on the updated tuple
    processed_items.sort(key=lambda x: x["sort_key"])
    print(f"   ✅ Sorted {len(processed_items)} questions primarily by Year/Exam, then Syllabus Taxonomy.")
    return processed_items, unmapped_errors

def generate_display_ids(sorted_items):
    print("\n🏷️ Step 5: Generating Display IDs with Conflict Resolution...")
    prefix_counters = defaultdict(int)
    final_questions = []

    for item in sorted_items:
        q = item["q"]
        prefix = f"PH-{item['u_code']}-{item['s_code']}-{item['exam']}{item['year']}"

        # Conflict Resolution: Increment counter per prefix
        prefix_counters[prefix] += 1
        serial_number = prefix_counters[prefix]

        q["display_id"] = f"{prefix}-{serial_number:02d}"
        final_questions.append(q)

    print("   ✅ Assigned unique display IDs successfully.")
    return final_questions

def process_repository():
    # Setup
    work_dir = extract_and_setup()
    questions_path, syllabus_path, images_dir = None, None, None

    for root, dirs, files_list in os.walk(work_dir):
        if "questions.json" in files_list: questions_path = os.path.join(root, "questions.json")
        if "syllabus.json" in files_list: syllabus_path = os.path.join(root, "syllabus.json")
        if "images" in dirs: images_dir = os.path.join(root, "images")

    if not questions_path or not syllabus_path:
        raise FileNotFoundError("Missing 'questions.json' or 'syllabus.json'.")

    # Load Data
    with open(questions_path, "r", encoding="utf-8") as f:
        questions = json.load(f)

    topic_map = build_taxonomy_map(syllabus_path)

    # 1. Pre-verification
    verification_errors = pre_verification(questions, images_dir)

    # 2 & 3. Assign Taxonomy and Sort
    sorted_items, mapping_errors = assign_and_sort(questions, topic_map)

    # 4. Assign Display IDs
    final_questions = generate_display_ids(sorted_items)

    # 5. Final Empty Metadata Check
    print("\n🔎 Step 6: Running Final Check for Empty Metadata...")
    final_empty_metadata = []
    for q in final_questions:
        q_md = str(q.get("question_markdown", "")).strip()
        q_meta = str(q.get("question_metadata", "")).strip()
        if not q_md and not q_meta:
            final_empty_metadata.append({"id": q.get("id"), "display_id": q.get("display_id")})

    if final_empty_metadata:
        print(f"   ⚠️ WARNING: {len(final_empty_metadata)} questions ended up with empty metadata/markdown.")
    else:
        print("   ✅ Final metadata check passed.")

    # Packaging
    print("\n📦 Step 7: Packaging Outputs...")
    out_dir = "final_output"
    if os.path.exists(out_dir): shutil.rmtree(out_dir)
    os.makedirs(out_dir)

    with open(os.path.join(out_dir, "mapped_questions.json"), "w", encoding="utf-8") as f:
        json.dump(final_questions, f, indent=2, ensure_ascii=False)

    if verification_errors:
        with open(os.path.join(out_dir, "error_pre_verification.json"), "w", encoding="utf-8") as f:
            json.dump(verification_errors, f, indent=2, ensure_ascii=False)

    if mapping_errors:
        with open(os.path.join(out_dir, "error_taxonomy_mapping.json"), "w", encoding="utf-8") as f:
            json.dump(mapping_errors, f, indent=2, ensure_ascii=False)

    if final_empty_metadata:
        with open(os.path.join(out_dir, "error_empty_metadata_final.json"), "w", encoding="utf-8") as f:
            json.dump(final_empty_metadata, f, indent=2, ensure_ascii=False)

    if images_dir and os.path.exists(images_dir):
        shutil.copytree(images_dir, os.path.join(out_dir, "images"))

    output_zip = "final_mapped_repository.zip"
    with zipfile.ZipFile(output_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for root, dirs, files_list in os.walk(out_dir):
            for file in files_list:
                file_path = os.path.join(root, file)
                zipf.write(file_path, os.path.relpath(file_path, out_dir))

    print("\n🎉 Process Complete!")
    print(f"   📊 Processed {len(final_questions)} Questions.")
    print(f"   📥 Initiating Download...")
    files.download(output_zip)

# Run the script
if __name__ == "__main__":
    process_repository()